# Generated by Django 4.1.2 on 2022-10-31 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_is_staff"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "사용자",
                "verbose_name_plural": "사용자 그룹",
            },
        ),
        migrations.RenameField(
            model_name="user", old_name="created_on", new_name="created_at",
        ),
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(max_length=10, unique=True, verbose_name="닉네임"),
        ),
    ]
