# Generated by Django 4.1.2 on 2022-10-31 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_auto_20210525_1739"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
